{
 "title": "Opflex endpoint <--> service [east-west]",
 "tags": [ "opflex" ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "endpoint to service [rate-5m]",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "rate(opflex_endpoint_to_svc_packets[5m])",
     "legendFormat": "\"{{ep_namespace}}:{{ep_name}}\" to \"{{svc_namespace}}:{{svc_name}}\""
    }
   ]
  },
  {
   "title": "service to endpoint [rate-5m]",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "rate(opflex_svc_to_endpoint_packets[5m])",
     "legendFormat": "\"{{svc_namespace}}:{{svc_name}}\" to \"{{ep_namespace}}:{{ep_name}}\""
    }
   ]
  },
  {
   "title": "Top 10 Pods consuming \"Kubernetes\" service [rate-5m]",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "topk(10, rate(opflex_svc_to_endpoint_packets{svc_name=\"kubernetes\"}[5m]))",
     "legendFormat": "\"{{svc_namespace}}:{{svc_name}}\" to \"{{ep_namespace}}:{{ep_name}}\""
    }
   ]
  },
  {
   "title": "Services used by Prometheus pod in cloud setup [rate-5m]",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "rate(opflex_endpoint_to_svc_packets{ep_namespace=\"monitoring\"}[5m])",
     "legendFormat": "\"{{ep_namespace}}:{{ep_name}}\" to \"{{svc_namespace}}:{{svc_name}}\""
    }
   ]
  }
 ]
}