{
 "title": "Opflex endpoints",
 "tags": [ "opflex" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Active local endpoints",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "opflex_active_local_endpoints" }
   ]
  },
  {
   "title": "Tx Packets",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "Pkts/sec" }
   ],
   "targets": [
    {
     "expr": "rate(opflex_endpoint_tx_packets[5m])"
    }
   ]
  },
  {
   "title": "Rx Packets",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "Pkts/sec" }
   ],
   "targets": [
    {
     "expr": "rate(opflex_endpoint_rx_packets[5m])"
    }
   ]
  },
  {
   "title": "Tx Dropped Packets",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "Pkts/sec" }
   ],
   "targets": [
    {
     "expr": "rate(opflex_endpoint_tx_drop_packets[5m])"
    }
   ]
  },
  {
   "title": "Rx Dropped Packets",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "Pkts/sec" }
   ],
   "targets": [
    {
     "expr": "rate(opflex_endpoint_rx_drop_packets[5m])"
    }
   ]
  }
 ]
}