{
 "title": "Opflex Service LB [external]",
 "tags": [ "opflex" ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Nginx ingress [rate-5m]",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (rate(opflex_svc_rx_packets{name=\"ngnix\",namespace=\"default\",scope=\"ext\"}[5m]))",
     "legendFormat": "svc=nginx, ns=default, scope=ext"
    }
   ]
  },
  {
   "title": "Nginx egress [rate-5m]",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (rate(opflex_svc_tx_packets{name=\"ngnix\",namespace=\"default\",scope=\"ext\"}[5m]))",
     "legendFormat": "svc=nginx, ns=default, scope=ext"
    }
   ]
  },
  {
   "title": "Nginx ingress per pod LB [rate-5m]",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "rate(opflex_svc_target_rx_packets{svc_name=\"ngnix\",svc_namespace=\"default\",svc_scope=\"ext\"}[5m])",
     "legendFormat": "pod={{ep_name}}, ns={{ep_namespace}}, node={{instance}}"
    }
   ]
  },
  {
   "title": "Nginx egress per pod LB [rate-5m]",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "rate(opflex_svc_target_tx_packets{svc_name=\"ngnix\",svc_namespace=\"default\",svc_scope=\"ext\"}[5m])",
     "legendFormat": "pod={{ep_name}}, ns={{ep_namespace}}, node={{instance}}"
    }
   ]
  }
 ]
}