{
 "title": "Opflex Service LB [nodePort]",
 "tags": [ "opflex" ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "top 5 services ingress [rate-5m]",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum by (name, namespace) (rate(opflex_svc_rx_packets{scope=\"nodePort\"}[5m])))",
     "legendFormat": "svc={{name}}, ns={{namespace}}"
    }
   ]
  },
  {
   "title": "top 5 services egress [rate-5m]",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum by (name, namespace) (rate(opflex_svc_tx_packets{scope=\"nodePort\"}[5m])))",
     "legendFormat": "svc={{name}}, ns={{namespace}}"
    }
   ]
  },
  {
   "title": "service-pod ingress [rate-5m]",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "rate(opflex_svc_target_rx_packets{svc_scope=\"nodePort\"}[5m])",
     "legendFormat": "pod={{ep_name}}, ns={{ep_namespace}}, node={{instance}}"
    }
   ]
  },
  {
   "title": "service-pod egress [rate-5m]",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "rate(opflex_svc_target_tx_packets{svc_scope=\"nodePort\"}[5m])",
     "legendFormat": "pod={{ep_name}}, ns={{ep_namespace}}, node={{instance}}"
    }
   ]
  },
  {
   "title": "prometheus-service ingress [rate-5m]",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum by (name,namespace) (rate(opflex_svc_rx_packets{name=\"prometheus-service\",namespace=\"monitoring\",scope=\"nodePort\"}[5m]))",
     "legendFormat": "svc={{name}}, ns={{namespace}}"
    }
   ]
  },
  {
   "title": "prometheus-service egress [rate-5m]",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum by (name,namespace) (rate(opflex_svc_tx_packets{name=\"prometheus-service\",namespace=\"monitoring\",scope=\"nodePort\"}[5m]))",
     "legendFormat": "svc={{name}}, ns={{namespace}}"
    }
   ]
  },
  {
   "title": "prometheus-service ingress per pod LB [rate-5m]",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "rate(opflex_svc_target_rx_packets{svc_name=\"prometheus-service\",svc_namespace=\"monitoring\",svc_scope=\"nodePort\"}[5m])",
     "legendFormat": "pod={{ep_name}}, ns={{ep_namespace}}, node={{instance}}"
    }
   ]
  },
  {
   "title": "prometheus-service egress per pod LB [rate-5m]",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "rate(opflex_svc_target_tx_packets{svc_name=\"prometheus-service\",svc_namespace=\"monitoring\",svc_scope=\"nodePort\"}[5m])",
     "legendFormat": "pod={{ep_name}}, ns={{ep_namespace}}, node={{instance}}"
    }
   ]
  }
 ]
}