/**
 * 
 * SOME COPYRIGHT
 * 
 * EpGroup.hpp
 * 
 * generated EpGroup.hpp file genie code generation framework free of license.
 *  
 */
#pragma once
#ifndef GI_GBP_EPGROUP_HPP
#define GI_GBP_EPGROUP_HPP

#include <boost/optional.hpp>
#include "opflex/modb/URIBuilder.h"
#include "opflex/modb/mo-internal/MO.h"
/*
 * contains: item:mclass(gbpe/InstContext)
 */
#include "opmodelgbp/gbpe/InstContext.hpp"
/*
 * contains: item:mclass(epdr/EndPointFromGroupRTgt)
 */
#include "opmodelgbp/epdr/EndPointFromGroupRTgt.hpp"
/*
 * contains: item:mclass(gbp/EpGroupToNetworkRSrc)
 */
#include "opmodelgbp/gbp/EpGroupToNetworkRSrc.hpp"
/*
 * contains: item:mclass(gbp/EpGroupToProvContractRSrc)
 */
#include "opmodelgbp/gbp/EpGroupToProvContractRSrc.hpp"
/*
 * contains: item:mclass(gbp/EpGroupToConsContractRSrc)
 */
#include "opmodelgbp/gbp/EpGroupToConsContractRSrc.hpp"

namespace opmodelgbp {
namespace gbp {

class EpGroup
    : public opflex::modb::mointernal::MO
{
public:

    /**
     * The unique class ID for EpGroup
     */
    static const opflex::modb::class_id_t CLASS_ID = 25;

    /**
     * Check whether name has been set
     * @return true if name has been set
     */
    bool isNameSet()
    {
        return getObjectInstance().isSet(819201ul, opflex::modb::PropertyInfo::STRING);
    }

    /**
     * Get the value of name if it has been set.
     * @return the value of name or boost::none if not set
     */
    boost::optional<const std::string&> getName()
    {
        if (isNameSet())
            return getObjectInstance().getString(819201ul);
        return boost::none;
    }

    /**
     * Get the value of name if set, otherwise the value of default passed in.
     * @param defaultValue default value returned if the property is not set
     * @return the value of name if set, otherwise the value of default passed in
     */
    const std::string& getName(const std::string& defaultValue)
    {
        return getName().get_value_or(defaultValue);
    }

    /**
     * Set name to the specified value in the currently-active mutator.
     * 
     * @param newValue the new value to set.
     * @return a reference to the current object
     * @throws std::logic_error if no mutator is active
     * @see opflex::modb::Mutator
     */
    opmodelgbp::gbp::EpGroup& setName(const std::string& newValue)
    {
        getTLMutator().modify(getClassId(), getURI())->setString(819201ul, newValue);
        return *this;
    }

    /**
     * Unset name in the currently-active mutator.
     * @throws std::logic_error if no mutator is active
     * @return a reference to the current object
     * @see opflex::modb::Mutator
     */
    opmodelgbp::gbp::EpGroup& unsetName()
    {
        getTLMutator().modify(getClassId(), getURI())->unset(819201ul, opflex::modb::PropertyInfo::STRING, opflex::modb::PropertyInfo::SCALAR);
        return *this;
    }

    /**
     * Retrieve an instance of EpGroup from the managed
     * object store.  If the object does not exist in the local store,
     * returns boost::none.  Note that even though it may not exist
     * locally, it may still exist remotely.
     * 
     * @param framework the framework instance to use
     * @param uri the URI of the object to retrieve
     * @return a shared pointer to the object or boost::none if it
     * does not exist.
     */
    static boost::optional<boost::shared_ptr<opmodelgbp::gbp::EpGroup> > resolve(
        opflex::ofcore::OFFramework& framework,
        const opflex::modb::URI& uri)
    {
        return opflex::modb::mointernal::MO::resolve<opmodelgbp::gbp::EpGroup>(framework, CLASS_ID, uri);
    }

    /**
     * Retrieve an instance of EpGroup from the managed
     * object store using the default framework instance.  If the 
     * object does not exist in the local store, returns boost::none. 
     * Note that even though it may not exist locally, it may still 
     * exist remotely.
     * 
     * @param uri the URI of the object to retrieve
     * @return a shared pointer to the object or boost::none if it
     * does not exist.
     */
    static boost::optional<boost::shared_ptr<opmodelgbp::gbp::EpGroup> > resolve(
        const opflex::modb::URI& uri)
    {
        return opflex::modb::mointernal::MO::resolve<opmodelgbp::gbp::EpGroup>(opflex::ofcore::OFFramework::defaultInstance(), CLASS_ID, uri);
    }

    /**
     * Retrieve an instance of EpGroup from the managed
     * object store by constructing its URI from the path elements
     * that lead to it.  If the object does not exist in the local
     * store, returns boost::none.  Note that even though it may not
     * exist locally, it may still exist remotely.
     * 
     * The object URI generated by this function will take the form:
     * /PolicyUniverse/PolicySpace/[policySpaceName]/GbpEpGroup/[gbpEpGroupName]
     * 
     * @param framework the framework instance to use 
     * @param policySpaceName the value of policySpaceName,
     * a naming property for Space
     * @param gbpEpGroupName the value of gbpEpGroupName,
     * a naming property for EpGroup
     * @return a shared pointer to the object or boost::none if it
     * does not exist.
     */
    static boost::optional<boost::shared_ptr<opmodelgbp::gbp::EpGroup> > resolve(
        opflex::ofcore::OFFramework& framework,
        const std::string& policySpaceName,
        const std::string& gbpEpGroupName)
    {
        return resolve(framework,opflex::modb::URIBuilder().addElement("PolicyUniverse").addElement("PolicySpace").addElement(policySpaceName).addElement("GbpEpGroup").addElement(gbpEpGroupName).build());
    }

    /**
     * Retrieve an instance of EpGroup from the 
     * default managed object store by constructing its URI from the
     * path elements that lead to it.  If the object does not exist in
     * the local store, returns boost::none.  Note that even though it
     * may not exist locally, it may still exist remotely.
     * 
     * The object URI generated by this function will take the form:
     * /PolicyUniverse/PolicySpace/[policySpaceName]/GbpEpGroup/[gbpEpGroupName]
     * 
     * @param policySpaceName the value of policySpaceName,
     * a naming property for Space
     * @param gbpEpGroupName the value of gbpEpGroupName,
     * a naming property for EpGroup
     * @return a shared pointer to the object or boost::none if it
     * does not exist.
     */
    static boost::optional<boost::shared_ptr<opmodelgbp::gbp::EpGroup> > resolve(
        const std::string& policySpaceName,
        const std::string& gbpEpGroupName)
    {
        return resolve(opflex::ofcore::OFFramework::defaultInstance(),policySpaceName,gbpEpGroupName);
    }

    /**
     * Retrieve the child object with the specified naming
     * properties. If the object does not exist in the local store,
     * returns boost::none.  Note that even though it may not exist
     * locally, it may still exist remotely.
     * 
     * @return a shared pointer to the object or boost::none if it
     * does not exist.
     */
    boost::optional<boost::shared_ptr<opmodelgbp::gbpe::InstContext> > resolveGbpeInstContext(
        )
    {
        return opmodelgbp::gbpe::InstContext::resolve(getFramework(), opflex::modb::URIBuilder(getURI()).addElement("GbpeInstContext").build());
    }

    /**
     * Create a new child object with the specified naming properties
     * and make it a child of this object in the currently-active
     * mutator.  If the object already exists in the store, get a
     * mutable copy of that object.  If the object already exists in
     * the mutator, get a reference to the object.
     * 
     * @throws std::logic_error if no mutator is active
     * @return a shared pointer to the (possibly new) object
     */
    boost::shared_ptr<opmodelgbp::gbpe::InstContext> addGbpeInstContext(
        )
    {
        boost::shared_ptr<opmodelgbp::gbpe::InstContext> result = addChild<opmodelgbp::gbpe::InstContext>(
            CLASS_ID, getURI(), 2148302871ul, 23,
            opflex::modb::URIBuilder(getURI()).addElement("GbpeInstContext").build()
            );
        return result;
    }

    /**
     * Retrieve the child object with the specified naming
     * properties. If the object does not exist in the local store,
     * returns boost::none.  Note that even though it may not exist
     * locally, it may still exist remotely.
     * 
     * @param epdrEndPointFromGroupRTgtSource the value of epdrEndPointFromGroupRTgtSource,
     * a naming property for EndPointFromGroupRTgt
     * @return a shared pointer to the object or boost::none if it
     * does not exist.
     */
    boost::optional<boost::shared_ptr<opmodelgbp::epdr::EndPointFromGroupRTgt> > resolveEpdrEndPointFromGroupRTgt(
        const std::string& epdrEndPointFromGroupRTgtSource)
    {
        return opmodelgbp::epdr::EndPointFromGroupRTgt::resolve(getFramework(), opflex::modb::URIBuilder(getURI()).addElement("EpdrEndPointFromGroupRTgt").addElement(epdrEndPointFromGroupRTgtSource).build());
    }

    /**
     * Create a new child object with the specified naming properties
     * and make it a child of this object in the currently-active
     * mutator.  If the object already exists in the store, get a
     * mutable copy of that object.  If the object already exists in
     * the mutator, get a reference to the object.
     * 
     * @param epdrEndPointFromGroupRTgtSource the value of epdrEndPointFromGroupRTgtSource,
     * a naming property for EndPointFromGroupRTgt
     * @throws std::logic_error if no mutator is active
     * @return a shared pointer to the (possibly new) object
     */
    boost::shared_ptr<opmodelgbp::epdr::EndPointFromGroupRTgt> addEpdrEndPointFromGroupRTgt(
        const std::string& epdrEndPointFromGroupRTgtSource)
    {
        boost::shared_ptr<opmodelgbp::epdr::EndPointFromGroupRTgt> result = addChild<opmodelgbp::epdr::EndPointFromGroupRTgt>(
            CLASS_ID, getURI(), 2148302872ul, 24,
            opflex::modb::URIBuilder(getURI()).addElement("EpdrEndPointFromGroupRTgt").addElement(epdrEndPointFromGroupRTgtSource).build()
            );
        result->setSource(epdrEndPointFromGroupRTgtSource);
        return result;
    }

    /**
     * Resolve and retrieve all of the immediate children of type
     * opmodelgbp::epdr::EndPointFromGroupRTgt
     * 
     * Note that this retrieves only those children that exist in the
     * local store.  It is possible that there are other children that
     * exist remotely.
     * 
     * The resulting managed objects will be added to the result
     * vector provided.
     * 
     * @param out a reference to a vector that will receive the child
     * objects.
     */
    void resolveEpdrEndPointFromGroupRTgt(/* out */ std::vector<boost::shared_ptr<opmodelgbp::epdr::EndPointFromGroupRTgt> >& out)
    {
        opflex::modb::mointernal::MO::resolveChildren<opmodelgbp::epdr::EndPointFromGroupRTgt>(
            getFramework(), CLASS_ID, getURI(), 2148302872ul, 24, out);
    }

    /**
     * Retrieve the child object with the specified naming
     * properties. If the object does not exist in the local store,
     * returns boost::none.  Note that even though it may not exist
     * locally, it may still exist remotely.
     * 
     * @return a shared pointer to the object or boost::none if it
     * does not exist.
     */
    boost::optional<boost::shared_ptr<opmodelgbp::gbp::EpGroupToNetworkRSrc> > resolveGbpEpGroupToNetworkRSrc(
        )
    {
        return opmodelgbp::gbp::EpGroupToNetworkRSrc::resolve(getFramework(), opflex::modb::URIBuilder(getURI()).addElement("GbpEpGroupToNetworkRSrc").build());
    }

    /**
     * Create a new child object with the specified naming properties
     * and make it a child of this object in the currently-active
     * mutator.  If the object already exists in the store, get a
     * mutable copy of that object.  If the object already exists in
     * the mutator, get a reference to the object.
     * 
     * @throws std::logic_error if no mutator is active
     * @return a shared pointer to the (possibly new) object
     */
    boost::shared_ptr<opmodelgbp::gbp::EpGroupToNetworkRSrc> addGbpEpGroupToNetworkRSrc(
        )
    {
        boost::shared_ptr<opmodelgbp::gbp::EpGroupToNetworkRSrc> result = addChild<opmodelgbp::gbp::EpGroupToNetworkRSrc>(
            CLASS_ID, getURI(), 2148302877ul, 29,
            opflex::modb::URIBuilder(getURI()).addElement("GbpEpGroupToNetworkRSrc").build()
            );
        return result;
    }

    /**
     * Retrieve the child object with the specified naming
     * properties. If the object does not exist in the local store,
     * returns boost::none.  Note that even though it may not exist
     * locally, it may still exist remotely.
     * 
     * @param gbpEpGroupToProvContractRSrcTargetClass the value of gbpEpGroupToProvContractRSrcTargetClass,
     * a naming property for EpGroupToProvContractRSrc
     * @param gbpEpGroupToProvContractRSrcTargetName the value of gbpEpGroupToProvContractRSrcTargetName,
     * a naming property for EpGroupToProvContractRSrc
     * @return a shared pointer to the object or boost::none if it
     * does not exist.
     */
    boost::optional<boost::shared_ptr<opmodelgbp::gbp::EpGroupToProvContractRSrc> > resolveGbpEpGroupToProvContractRSrc(
        const std::string& gbpEpGroupToProvContractRSrcTargetName)
    {
        opflex::modb::class_id_t gbpEpGroupToProvContractRSrcTargetClass = 28;
        return opmodelgbp::gbp::EpGroupToProvContractRSrc::resolve(getFramework(), opflex::modb::URIBuilder(getURI()).addElement("GbpEpGroupToProvContractRSrc").addElement(gbpEpGroupToProvContractRSrcTargetClass).addElement(gbpEpGroupToProvContractRSrcTargetName).build());
    }

    /**
     * Create a new child object with the specified naming properties
     * and make it a child of this object in the currently-active
     * mutator.  If the object already exists in the store, get a
     * mutable copy of that object.  If the object already exists in
     * the mutator, get a reference to the object.
     * 
     * @param gbpEpGroupToProvContractRSrcTargetClass the value of gbpEpGroupToProvContractRSrcTargetClass,
     * a naming property for EpGroupToProvContractRSrc
     * @param gbpEpGroupToProvContractRSrcTargetName the value of gbpEpGroupToProvContractRSrcTargetName,
     * a naming property for EpGroupToProvContractRSrc
     * @throws std::logic_error if no mutator is active
     * @return a shared pointer to the (possibly new) object
     */
    boost::shared_ptr<opmodelgbp::gbp::EpGroupToProvContractRSrc> addGbpEpGroupToProvContractRSrc(
        const std::string& gbpEpGroupToProvContractRSrcTargetName)
    {
        opflex::modb::class_id_t gbpEpGroupToProvContractRSrcTargetClass = 28;
        boost::shared_ptr<opmodelgbp::gbp::EpGroupToProvContractRSrc> result = addChild<opmodelgbp::gbp::EpGroupToProvContractRSrc>(
            CLASS_ID, getURI(), 2148302886ul, 38,
            opflex::modb::URIBuilder(getURI()).addElement("GbpEpGroupToProvContractRSrc").addElement(gbpEpGroupToProvContractRSrcTargetClass).addElement(gbpEpGroupToProvContractRSrcTargetName).build()
            );
        result->setTargetContract(opflex::modb::URI(gbpEpGroupToProvContractRSrcTargetName));
        return result;
    }

    /**
     * Resolve and retrieve all of the immediate children of type
     * opmodelgbp::gbp::EpGroupToProvContractRSrc
     * 
     * Note that this retrieves only those children that exist in the
     * local store.  It is possible that there are other children that
     * exist remotely.
     * 
     * The resulting managed objects will be added to the result
     * vector provided.
     * 
     * @param out a reference to a vector that will receive the child
     * objects.
     */
    void resolveGbpEpGroupToProvContractRSrc(/* out */ std::vector<boost::shared_ptr<opmodelgbp::gbp::EpGroupToProvContractRSrc> >& out)
    {
        opflex::modb::mointernal::MO::resolveChildren<opmodelgbp::gbp::EpGroupToProvContractRSrc>(
            getFramework(), CLASS_ID, getURI(), 2148302886ul, 38, out);
    }

    /**
     * Retrieve the child object with the specified naming
     * properties. If the object does not exist in the local store,
     * returns boost::none.  Note that even though it may not exist
     * locally, it may still exist remotely.
     * 
     * @param gbpEpGroupToConsContractRSrcTargetClass the value of gbpEpGroupToConsContractRSrcTargetClass,
     * a naming property for EpGroupToConsContractRSrc
     * @param gbpEpGroupToConsContractRSrcTargetName the value of gbpEpGroupToConsContractRSrcTargetName,
     * a naming property for EpGroupToConsContractRSrc
     * @return a shared pointer to the object or boost::none if it
     * does not exist.
     */
    boost::optional<boost::shared_ptr<opmodelgbp::gbp::EpGroupToConsContractRSrc> > resolveGbpEpGroupToConsContractRSrc(
        const std::string& gbpEpGroupToConsContractRSrcTargetName)
    {
        opflex::modb::class_id_t gbpEpGroupToConsContractRSrcTargetClass = 28;
        return opmodelgbp::gbp::EpGroupToConsContractRSrc::resolve(getFramework(), opflex::modb::URIBuilder(getURI()).addElement("GbpEpGroupToConsContractRSrc").addElement(gbpEpGroupToConsContractRSrcTargetClass).addElement(gbpEpGroupToConsContractRSrcTargetName).build());
    }

    /**
     * Create a new child object with the specified naming properties
     * and make it a child of this object in the currently-active
     * mutator.  If the object already exists in the store, get a
     * mutable copy of that object.  If the object already exists in
     * the mutator, get a reference to the object.
     * 
     * @param gbpEpGroupToConsContractRSrcTargetClass the value of gbpEpGroupToConsContractRSrcTargetClass,
     * a naming property for EpGroupToConsContractRSrc
     * @param gbpEpGroupToConsContractRSrcTargetName the value of gbpEpGroupToConsContractRSrcTargetName,
     * a naming property for EpGroupToConsContractRSrc
     * @throws std::logic_error if no mutator is active
     * @return a shared pointer to the (possibly new) object
     */
    boost::shared_ptr<opmodelgbp::gbp::EpGroupToConsContractRSrc> addGbpEpGroupToConsContractRSrc(
        const std::string& gbpEpGroupToConsContractRSrcTargetName)
    {
        opflex::modb::class_id_t gbpEpGroupToConsContractRSrcTargetClass = 28;
        boost::shared_ptr<opmodelgbp::gbp::EpGroupToConsContractRSrc> result = addChild<opmodelgbp::gbp::EpGroupToConsContractRSrc>(
            CLASS_ID, getURI(), 2148302891ul, 43,
            opflex::modb::URIBuilder(getURI()).addElement("GbpEpGroupToConsContractRSrc").addElement(gbpEpGroupToConsContractRSrcTargetClass).addElement(gbpEpGroupToConsContractRSrcTargetName).build()
            );
        result->setTargetContract(opflex::modb::URI(gbpEpGroupToConsContractRSrcTargetName));
        return result;
    }

    /**
     * Resolve and retrieve all of the immediate children of type
     * opmodelgbp::gbp::EpGroupToConsContractRSrc
     * 
     * Note that this retrieves only those children that exist in the
     * local store.  It is possible that there are other children that
     * exist remotely.
     * 
     * The resulting managed objects will be added to the result
     * vector provided.
     * 
     * @param out a reference to a vector that will receive the child
     * objects.
     */
    void resolveGbpEpGroupToConsContractRSrc(/* out */ std::vector<boost::shared_ptr<opmodelgbp::gbp::EpGroupToConsContractRSrc> >& out)
    {
        opflex::modb::mointernal::MO::resolveChildren<opmodelgbp::gbp::EpGroupToConsContractRSrc>(
            getFramework(), CLASS_ID, getURI(), 2148302891ul, 43, out);
    }

    /**
     * Remove this instance using the currently-active mutator.  If
     * the object does not exist, then this will be a no-op.  If this
     * object has any children, they will be garbage-collected at some
     * future time.
     * 
     * @throws std::logic_error if no mutator is active
     */
    void remove()
    {
        getTLMutator().remove(CLASS_ID, getURI());
    }

    /**
     * Remove the EpGroup object with the specified URI
     * using the currently-active mutator.  If the object does not exist,
     * then this will be a no-op.  If this object has any children, they
     * will be garbage-collected at some future time.
     * 
     * @param framework the framework instance to use
     * @param uri the URI of the object to remove
     * @throws std::logic_error if no mutator is active
     */
    static void remove(opflex::ofcore::OFFramework& framework,
                       const opflex::modb::URI& uri)
    {
        MO::remove(framework, CLASS_ID, uri);
    }

    /**
     * Remove the EpGroup object with the specified URI 
     * using the currently-active mutator and the default framework 
     * instance.  If the object does not exist, then this will be a
     * no-op.  If this object has any children, they will be 
     * garbage-collected at some future time.
     * 
     * @param uri the URI of the object to remove
     * @throws std::logic_error if no mutator is active
     */
    static void remove(const opflex::modb::URI& uri)
    {
        remove(opflex::ofcore::OFFramework::defaultInstance(), uri);
    }

    /**
     * Remove the EpGroup object with the specified path
     * elements from the managed object store.  If the object does
     * not exist, then this will be a no-op.  If this object has any
     * children, they will be garbage-collected at some future time.
     * 
     * The object URI generated by this function will take the form:
     * /PolicyUniverse/PolicySpace/[policySpaceName]/GbpEpGroup/[gbpEpGroupName]
     * 
     * @param framework the framework instance to use
     * @param policySpaceName the value of policySpaceName,
     * a naming property for Space
     * @param gbpEpGroupName the value of gbpEpGroupName,
     * a naming property for EpGroup
     * @throws std::logic_error if no mutator is active
     */
    static void remove(
        opflex::ofcore::OFFramework& framework,
        const std::string& policySpaceName,
        const std::string& gbpEpGroupName)
    {
        MO::remove(framework, CLASS_ID, opflex::modb::URIBuilder().addElement("PolicyUniverse").addElement("PolicySpace").addElement(policySpaceName).addElement("GbpEpGroup").addElement(gbpEpGroupName).build());
    }

    /**
     * Remove the EpGroup object with the specified path
     * elements from the managed object store using the default
     * framework instance.  If the object does not exist, then
     * this will be a no-op.  If this object has any children, they
     * will be garbage-collected at some future time.
     * 
     * The object URI generated by this function will take the form:
     * /PolicyUniverse/PolicySpace/[policySpaceName]/GbpEpGroup/[gbpEpGroupName]
     * 
     * @param policySpaceName the value of policySpaceName,
     * a naming property for Space
     * @param gbpEpGroupName the value of gbpEpGroupName,
     * a naming property for EpGroup
     * @throws std::logic_error if no mutator is active
     */
    static void remove(
        const std::string& policySpaceName,
        const std::string& gbpEpGroupName)
    {
        remove(opflex::ofcore::OFFramework::defaultInstance(),policySpaceName,gbpEpGroupName);
    }

    /**
     * Register a listener that will get called for changes related to
     * this class.  This listener will be called for any modifications
     * of this class or any transitive children of this class.
     * 
     * @param framework the framework instance 
     * @param listener the listener functional object that should be
     * called when changes occur related to the class.  This memory is
     * owned by the caller and should be freed only after it has been
     * unregistered.
     */
    static void registerListener(
        opflex::ofcore::OFFramework& framework,
        opflex::modb::ObjectListener* listener)
    {
        opflex::modb::mointernal
            ::MO::registerListener(framework, listener, CLASS_ID);
    }

    /**
     * Register a listener that will get called for changes related to
     * this class with the default framework instance.  This listener
     * will be called for any modifications of this class or any
     * transitive children of this class.
     * 
     * @param listener the listener functional object that should be
     * called when changes occur related to the class.  This memory is
     * owned by the caller and should be freed only after it has been
     * unregistered.
     */
    static void registerListener(
        opflex::modb::ObjectListener* listener)
    {
        registerListener(opflex::ofcore::OFFramework::defaultInstance(), listener);
    }

    /**
     * Unregister a listener from updates to this class.
     * 
     * @param framework the framework instance 
     * @param listener The listener to unregister.
     */
    static void unregisterListener(
        opflex::ofcore::OFFramework& framework,
        opflex::modb::ObjectListener* listener)
    {
        opflex::modb::mointernal
            ::MO::unregisterListener(framework, listener, CLASS_ID);
    }

    /**
     * Unregister a listener from updates to this class from the
     * default framework instance
     * 
     * @param listener The listener to unregister.
     */
    static void unregisterListener(
        opflex::modb::ObjectListener* listener)
    {
        unregisterListener(opflex::ofcore::OFFramework::defaultInstance(), listener);
    }

    /**
     * Construct an instance of EpGroup.
     * This should not typically be called from user code.
     */
    EpGroup(
        opflex::ofcore::OFFramework& framework,
        const opflex::modb::URI& uri,
        const boost::shared_ptr<const opflex::modb::mointernal::ObjectInstance>& oi)
        : MO(framework, CLASS_ID, uri, oi) { }
}; // class EpGroup

} // namespace gbp
} // namespace opmodelgbp
#endif // GI_GBP_EPGROUP_HPP
