#ifndef VPPAPIERROR_H
#define VPPAPIERROR_H

namespace ovsagent {
//Error Api Class
#define UNSPECIFIED  -1 // "Unspecified Error"
#define INVALID_SW_IF_INDEX  -2 // "Invalid sw_if_index"
#define NO_SUCH_FIB -3 // "No such FIB / VRF"
#define NO_SUCH_INNER_FIB -4 // "No such inner FIB / VRF"
#define NO_SUCH_LABEL -5 // "No such label"
#define NO_SUCH_ENTRY -6 // "No such entry"
#define INVALID_VALUE -7 // "Invalid value"
#define INVALID_VALUE_2 -8 // "Invalid value #2"
#define UNIMPLEMENTED -9 // "Unimplemented"
#define INVALID_SW_IF_INDEX_2 -10 // "Invalid sw_if_index #2"
//SYSCALL_ERROR_1, -11, "System call error #1"
//SYSCALL_ERROR_2, -12, "System call error #2"
//SYSCALL_ERROR_3, -13, "System call error #3"
//SYSCALL_ERROR_4, -14, "System call error #4"
//SYSCALL_ERROR_5, -15, "System call error #5"
//SYSCALL_ERROR_6, -16, "System call error #6"
//SYSCALL_ERROR_7, -17, "System call error #7"
//SYSCALL_ERROR_8, -18, "System call error #8"
//SYSCALL_ERROR_9, -19, "System call error #9"
//SYSCALL_ERROR_10, -20, "System call error #10"
#define FEATURE_DISABLED -30 // "Feature disabled by configuration"
#define INVALID_REGISTRATION -31 // "Invalid registration"
#define NEXT_HOP_NOT_IN_FIB  -50 // "Next hop not in FIB"
#define UNKNOWN_DESTINATION -51 //"Unknown destination"
#define PREFIX_MATCHES_NEXT_HOP -52 // "Prefix matches next hop"
#define NEXT_HOP_NOT_FOUND_MP -53 // "Next hop not found (multipath)"
#define NO_MATCHING_INTERFACE -54 // "No matching interface for probe"
#define INVALID_VLAN -55 // "Invalid VLAN"
#define VLAN_ALREADY_EXISTS -56 // "VLAN subif already exists"
#define INVALID_SRC_ADDRESS -57 // "Invalid src address"
#define INVALID_DST_ADDRESS -58 // "Invalid dst address"
#define ADDRESS_LENGTH_MISMATCH -59 // "Address length mismatch"
#define ADDRESS_NOT_FOUND_FOR_INTERFACE -60 // "Address not found for interface"
#define ADDRESS_NOT_LINK_LOCAL -61 // "Address not link-local"
#define IP6_NOT_ENABLED -62 // "ip6 not enabled"
#define IN_PROGRESS 10 // "Operation in progress"
#define NO_SUCH_NODE -63 // "No such graph node"
#define NO_SUCH_NODE2 -64 // "No such graph node #2"
#define NO_SUCH_TABLE -65 // "No such table"
#define NO_SUCH_TABLE2 -66 // "No such table #2"
#define NO_SUCH_TABLE3 -67 // "No such table #3"
#define SUBIF_ALREADY_EXISTS -68 // "Subinterface already exists"
#define SUBIF_CREATE_FAILED -69 // "Subinterface creation failed"
#define INVALID_MEMORY_SIZE -70 // "Invalid memory size requested"
#define INVALID_INTERFACE -71 // "Invalid interface"
#define INVALID_VLAN_TAG_COUNT -72  // "Invalid number of tags for requested operation"
#define INVALID_ARGUMENT -73 // "Invalid argument"
#define UNEXPECTED_INTF_STATE -74 // "Unexpected interface state"
#define TUNNEL_EXIST -75 // "Tunnel already exists"
#define INVALID_DECAP_NEXT -76 // "Invalid decap-next"
#define RESPONSE_NOT_READY -77 // "Response not ready"
#define NOT_CONNECTED -78 // "Not connected to the data plane"
#define IF_ALREADY_EXISTS -79 // "Interface already exists"
#define BOND_SLAVE_NOT_ALLOWED -80 // "Operation not allowed on slave of BondEthernet" 
#define VALUE_EXIST -81 // "Value already exists"
#define SAME_SRC_DST -82 // "Source and destination are the same"
#define IP6_MULTICAST_ADDRESS_NOT_PRESENT -83 // "IP6 multicast address required"
#define SR_POLICY_NAME_NOT_PRESENT -84 // "Segement routing policy name required"
#define NOT_RUNNING_AS_ROOT -85 // "Not running as root"
#define ALREADY_CONNECTED -86 // "Connection to the data plane already exists"
#define UNSUPPORTED_JNI_VERSION -87 // "Unsupported JNI version"
#define FAILED_TO_ATTACH_TO_JAVA_THREAD -88 // "Failed to attach to Java thread"
#define INVALID_WORKER -89 // "Invalid worker thread"
#define LISP_DISABLED  -90 // "LISP is disabled"
#define CLASSIFY_TABLE_NOT_FOUND -91 // "Classify table not found"
#define INVALID_EID_TYPE -92 // "Unsupported LSIP EID type"
#define CANNOT_CREATE_PCAP_FILE -93 // "Cannot create pcap file"
#define INCORRECT_ADJACENCY_TYPE -94 // "Invalid adjacency type for this operation"
#define EXCEEDED_NUMBER_OF_RANGES_CAPACITY -95 // "Operation would exceed configured capacity of ranges"
#define EXCEEDED_NUMBER_OF_PORTS_CAPACITY -96 // "Operation would exceed capacity of number of ports"
#define INVALID_ADDRESS_FAMILY -97 // "Invalid address family"
#define INVALID_SUB_SW_IF_INDEX -98 // "Invalid sub-interface sw_if_index"
#define TABLE_TOO_BIG -99 // "Table too big"
#define CANNOT_ENABLE_DISABLE_FEATURE -100 // "Cannot enable/disable feature"
#define BFD_EEXIST -101 // "Duplicate BFD object"
#define BFD_ENOENT -102 // "No such BFD object"
#define BFD_EINUSE -103 // "BFD object in use"
#define BFD_NOTSUPP -104 // "BFD feature not supported"
#define ADDRESS_IN_USE -105 // "Address in use"
#define ADDRESS_NOT_IN_USE -106 // "Address not in use"
#define QUEUE_FULL -107 // "Queue full"
#define UNKNOWN_URI_TYPE  -108 // "Unknown URI type"
#define URI_FIFO_CREATE_FAILED -109 // "URI FIFO segment create failed"
#define LISP_RLOC_LOCAL -110 // "RLOC address is local"
#define BFD_EAGAIN -111 // "BFD object cannot be manipulated at this time"
#define INVALID_GPE_MODE -112 // "Invalid GPE mode"
#define LISP_GPE_ENTRIES_PRESENT -113 // "LISP GPE entries are present"
#define ADDRESS_FOUND_FOR_INTERFACE -114 // "Address found for interface"
#define SESSION_CONNECT_FAIL -115 // "Session failed to connect"
#define ENTRY_ALREADY_EXISTS -116 // "Entry already exists"
#define SVM_SEGMENT_CREATE_FAIL -117 // "svm segment create fail"
#define APPLICATION_NOT_ATTACHED -118 // "application not attached"
#define BD_ALREADY_EXISTS -119 // "Bridge domain already exists"
#define BD_IN_USE -120 // "Bridge domain has member interfaces"
#define BD_NOT_MODIFIABLE -121 // "Bridge domain 0 can't be deleted/modified"
#define BD_ID_EXCEED_MAX -122 // "Bridge domain ID exceed 16M limit"
#define UNSUPPORTED -123 // "Unsupported"
}

#endif /* VPPAPIERROR_H */
